on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Getting git commit data
        uses: rlespinasse/git-commit-data-action@v1

      - name: Autodeployment Production
        if: github.ref == 'refs/heads/master'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/insoft/public_html/posi
            git checkout master
            git pull origin master
            git push all master
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
